<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation Form</title>
</head>
<body>
    <h2>Reservation Form</h2>
    <form action="submit_reservation.php" method="POST">
        <label for="name">Full Name:</label>
        <input type="text" id="name" name="name" required><br><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="phone">Phone Number:</label>
        <input type="tel" id="phone" name="phone" required><br><br>

        <label for="date">Reservation Date:</label>
        <input type="date" id="date" name="date" required><br><br>

        <label for="time">Time:</label>
        <input type="time" id="time" name="time" required><br><br>

        <label for="guests">Number of Guests:</label>
        <input type="number" id="guests" name="guests" min="1" required><br><br>

        <label for="comments">Special Requests:</label><br>
        <textarea id="comments" name="comments" rows="4"></textarea><br><br>

        <input type="submit" value="Reserve">
    </form>
</body>
</html>
<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = htmlspecialchars($_POST['name']);
    $email = htmlspecialchars($_POST['email']);
    $phone = htmlspecialchars($_POST['phone']);
    $date = $_POST['date'];
    $time = $_POST['time'];
    $guests = $_POST['guests'];
    $comments = htmlspecialchars($_POST['comments']);

    // You can store this in a database (MySQL) or send it via email
    $to = "your_email@example.com";
    $subject = "New Reservation from $name";
    $message = "Name: $name\nEmail: $email\nPhone: $phone\nDate: $date\nTime: $time\nGuests: $guests\nRequests: $comments";
    $headers = "From: $email";

    if (mail($to, $subject, $message, $headers)) {
        echo "Reservation successful!";
    } else {
        echo "Error submitting reservation.";
    }
}
?>
